export const countries = [
    { name: "Qatar", code: "QA", dialCode: "+974" },
    { name: "United Arab Emirates", code: "AE", dialCode: "+971" },
    { name: "Saudi Arabia", code: "SA", dialCode: "+966" },
    { name: "Oman", code: "OM", dialCode: "+968" },
    { name: "Kuwait", code: "KW", dialCode: "+965" },
    { name: "Bahrain", code: "BH", dialCode: "+973" },
    { name: "India", code: "IN", dialCode: "+91" },
    { name: "United Kingdom", code: "GB", dialCode: "+44" },
    { name: "United States", code: "US", dialCode: "+1" },
    { name: "Canada", code: "CA", dialCode: "+1" },
    { name: "Australia", code: "AU", dialCode: "+61" },
    { name: "Pakistan", code: "PK", dialCode: "+92" },
    { name: "Philippines", code: "PH", dialCode: "+63" },
    { name: "Egypt", code: "EG", dialCode: "+20" },
    { name: "Jordan", code: "JO", dialCode: "+962" },
    { name: "Lebanon", code: "LB", dialCode: "+961" },
    { name: "Turkey", code: "TR", dialCode: "+90" },
    { name: "France", code: "FR", dialCode: "+33" },
    { name: "Germany", code: "DE", dialCode: "+49" },
    { name: "Italy", code: "IT", dialCode: "+39" },
    { name: "Spain", code: "ES", dialCode: "+34" },
    { name: "Russia", code: "RU", dialCode: "+7" },
    { name: "China", code: "CN", dialCode: "+86" },
    { name: "Japan", code: "JP", dialCode: "+81" },
    { name: "Singapore", code: "SG", dialCode: "+65" },
    { name: "Malaysia", code: "MY", dialCode: "+60" },
    { name: "Sri Lanka", code: "LK", dialCode: "+94" },
    { name: "Bangladesh", code: "BD", dialCode: "+880" },
];
